### PR TITLE
Fix floating formatting

### LINKED ISSUE #58: Bug Report: Incorrect Duration Formatting (Scientific Notation)
When a M3u8::SegmentItem is initialized with a very small float/decimal duration, the to_s method outputs the #EXTINF value in scientific notation (e.g., 1.0e-05).

According to the HLS ([RFC 8216](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.2.1)) specification, the duration should be formatted as a floating-point number or integer to ensure compatibility with all players.

##### Steps to Reproduce

Execute the following Ruby code:

```rb
M3u8::SegmentItem.new(program_date_time: Time.now, duration: 0.00001, segment: 'http://example.com/segment-1.aac').to_s
```

##### Actual Behavior

The duration is rendered in scientific notation:

```
"#EXTINF:1.0e-05,\n#EXT-X-PROGRAM-DATE-TIME:2026-03-09T09:19:07+09:00\nhttp://example.com/segment-1.aac"
```

##### Expected Behavior

```
"#EXTINF:0.00001,\n#EXT-X-PROGRAM-DATE-TIME:2026-03-09T09:19:07+09:00\nhttp://example.com/segment-1.aac"
```

Tested in 
```sh
$ ruby -v
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin24]
$ gem list | grep m3u8
m3u8 (1.7.0)
```

### PR DESCRIPTION
**Pull request by marocchino**
close #58

### CODE REVIEW

File: lib/m3u8/segment_item.rb [hunk 1]
```diff
@@ -32,10 +34,19 @@ def self.parse(text)
...
+      "#EXTINF:#{float_format(duration)},#{comment}#{byterange_format}" \
         "\n#{date_format}#{segment}"
     end
 
+    def float_format(number)
+      case duration
+      when Float
+        BigDecimal(number).to_s('F')
+      else
+        number.to_s
```
Comment (marocchino) [inline lib/m3u8/segment_item.rb]:
```rb
> BigDecimal(10).to_s('F')
=> "10.0"
```
However, the [original test](https://github.com/marocchino/m3u8/blob/988cf222f30473255247b20af415bbc1c83a4eb8/spec/lib/m3u8/segment_item_spec.rb#L87) expects the result to be 10, so I added a conditional branch to handle this.

File: lib/m3u8/segment_item.rb [hunk 2]
```diff
@@ -32,10 +34,19 @@ def self.parse(text)
...
     def to_s
-      "#EXTINF:#{duration},#{comment}#{byterange_format}" \
+      "#EXTINF:#{float_format(duration)},#{comment}#{byterange_format}" \
         "\n#{date_format}#{segment}"
     end
 
+    def float_format(number)
+      case duration
+      when Float
+        BigDecimal(number).to_s('F')
```
Comment (marocchino) [inline lib/m3u8/segment_item.rb]:
```sh
$ cat bench.rb
# frozen_string_literal: true

require 'benchmark/ips'
require 'bigdecimal'

def format_sub(num)
  format('%f', num).sub(/\.?0+$/, '')
end

def big_decimal(num)
  BigDecimal(num).to_s('F')
end

Benchmark.ips do |x|
  x.report('format_sub') { format_sub(1.23456789) }
  x.report('big_decimal') { big_decimal(1.23456789) }
  x.compare!
end
$ ruby bench.rb
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
Warming up --------------------------------------
          format_sub   126.984k i/100ms
         big_decimal   164.232k i/100ms
Calculating -------------------------------------
          format_sub      1.273M (± 0.7%) i/s  (785.70 ns/i) -      6.476M in   5.088579s
         big_decimal      1.638M (± 0.7%) i/s  (610.61 ns/i) -      8.212M in   5.014346s

Comparison:
         big_decimal:  1637706.2 i/s
          format_sub:  1272746.5 i/s - 1.29x  slower

```

**Comment by sethdeckard** [comment]
Hi @marocchino thank you for the PR, would you please address the following?

  - Fix spec.dependencies (should be `add_dependency`)
  - Move float_format to AttributeFormatter (looks like we'll need it for other types that have this same issue and I thought this was better than making it private).
 
The same issue exists in PartItem and DateRangeItem via unquoted_format  but I can handle this if you just want to keep this PR focused, up to you.

**Review by sethdeckard — APPROVED** [review]
LGTM, thank you!

**Comment by sethdeckard** [comment]
@marocchino released in 1.8.1
